# Generated by Django 5.2.8 on 2025-12-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='tickets',
            field=models.IntegerField(default=1),
        ),
    ]
