# Generated by Django 5.2.8 on 2025-12-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_wishlistitem_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='isPast',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
